ARDUINO_DIR  = /usr/share/arduino
AVR_TOOLS_PATH = /usr/bin

TARGET       = CLItest
ARDUINO_LIBS = LiquidCrystal

BOARD_TAG    = nano
ARDUINO_PORT = /dev/ttyUSB*

include /usr/share/arduino/Arduino.mk
